# Task List 2

In [8]:
import sys
import os
import numpy as np
sys.path.insert(1, os.sep.join(["..", "packages"]))
from multivare import MN_distribution, Cholesky_factor, tau_2_dim, multivate_characteristic_r_i
from alphastable import *


## Task 1

## Task 2

## Task 3

## Task 4

We use Cholesky factor to generate L such that L @ L.T = Sigma <br />
X = L @ Z + mu

In [6]:

A_ = []
A_.append(np.array([[1,1/2], [1/2,4]]))
A_.append(np.array([[1,1/2, 1/3], [1/2,4, 1/4], [1/3, 1/4, 3]]))
A_.append(np.array([[1,1/2, 1/3, 1/5], [1/2, 2, 1/4, 1/6],
    [1/3, 1/4, 3, 1/7], [1/5, 1/6, 1/7, 4]]))

for A in A_:
    L = Cholesky_factor(A)
    print(L)
    print("Powinno być 0: ", (A - L @ L.T).sum())
    print()

[[1.         0.        ]
 [0.5        1.93649167]]
Powinno być 0:  0.0

[[1.         0.         0.        ]
 [0.5        1.93649167 0.        ]
 [0.33333333 0.04303315 1.69912832]]
Powinno być 0:  4.440892098500626e-16

[[1.         0.         0.         0.        ]
 [0.5        1.32287566 0.         0.        ]
 [0.33333333 0.06299408 1.69850541 0.        ]
 [0.2        0.05039526 0.04298831 1.98887212]]
Powinno być 0:  0.0



In [4]:
N4 = 1000
Sigma4 = np.array([[1,1/2, 1/3, 1/5], [1/2, 2, 1/4, 1/6],
    [1/3, 1/4, 3, 1/7], [1/5, 1/6, 1/7, 4]])
mu4 = np.array([-3,1,0,5])
MN_distribution(N4, mu4, Sigma4)

array([[-3.62582917, -0.61723519, -1.48757827,  1.58288817],
       [-2.95982798,  1.37139033,  0.68402605,  6.3343849 ],
       [-3.97039926, -0.53472565, -0.74819798,  0.89171974],
       ...,
       [-1.49860221,  0.12497989,  1.58796815,  7.24071089],
       [-3.70103879,  0.5077933 ,  0.60440425,  4.28062683],
       [-3.42918789,  2.17192681, -0.03117661,  3.35673899]])

## Task 5

## Task 6

$\Phi_{\alpha}(\varTheta) = \mathbf{E}e^{i (\varTheta \circ X)}$

Y = multivare_alphastable(2 * N, 1, alpha, 1/2, 0.25, 1, 1)


## Task 7

$\tau_{X,Y} = \| X \|_{\alpha} ^{\alpha} + \| Y \|_{\alpha} ^{\alpha} - \| X - Y \|_{\alpha} ^{\alpha}$ <br />
$\tau_{X[0],X[1]} = \| X[0] \|_{\alpha} ^{\alpha} + \| X[1] \|_{\alpha} ^{\alpha} - \| X[0] - X[1] \|_{\alpha} ^{\alpha}$

In [12]:
alpha = 0.9
N = 10 ** 4
gamma = [0.25, 0.125, 0.25, 0.25, 0.125, 0.25]
points = [[1, 0], [0.5, np.sqrt(3)/2],
            [-1/2, np.sqrt(3)/2], [-1, 0],
            [-1/2, -np.sqrt(3)/2], [1/2, -np.sqrt(3)/2]]

X = multivariate_alphastable(alpha, gamma, points, N)
Y = alphastable(2 * N, 1, alpha, 1/2, 0.25, 1, 1)
print(tau_2_dim(X))

Y = Y.reshape(N,2)

print(tau_2_dim(Y))

[0.32169050084460427, 0.006623416076310333]
[0.0039574461630546565, -0.007452492215433537]
